import turtle
bob = turtle.Turtle() 
bob.penup()
bob.goto(-200,200)
bob.pendown()
bob.speed(1000)
def squarer():
  for x in range(4):
    bob.forward(20)
    bob.right(90)  
def squarel():
  for x in range(4):
    bob.forward(20)
    bob.left(90)  
bob.color("#B5B4B4")
for i in range(21):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(9):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
for i in range(3):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(7):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#B5B4B4")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(6):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(6):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(6):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(6):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(8):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("white")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(3):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EFF65B")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EFF65B")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC3514")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EFF65B")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#B5B4B4")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(10):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.color("#B5B4B4")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(9):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#B5B4B4")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.color("#B5B4B4")
for i in range(5):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EFF65B")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(5):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(3):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#B5B4B4")
for i in range(4):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EFF65B")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(5):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.color("#B5B4B4")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("white")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EFF65B")
for i in range(3):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(5):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#B5B4B4")
for i in range(6):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#EFF65B")
for i in range(2):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(3):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(5):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.color("#B5B4B4")
for i in range(8):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(3):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#EC8314")
for i in range(1):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(2):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(7):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.color("#B5B4B4")
for i in range(7):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("white")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("white")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(1):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(9):
    bob.begin_fill()
    squarel()
    bob.end_fill()
    bob.forward(20)
bob.left(90)
bob.forward(20)
bob.left(90)
bob.color("#B5B4B4")
for i in range(10):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#282524")
for i in range(4):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
bob.color("#B5B4B4")
for i in range(7):
    bob.begin_fill()
    squarer()
    bob.end_fill()
    bob.forward(20)
input()